// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: accessors.proto

/*
Package accessors is a generated protocol buffer package.

It is generated from these files:
	accessors.proto

It has these top-level messages:
	MessageEvent
*/
package accessors

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// MessageEvent is a MessageEvent from a connected network.
type MessageEvent struct {
	Sender *MessageEvent_Sender `protobuf:"bytes,1,opt,name=sender" json:"sender,omitempty"`
	Origin string               `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Body   string               `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (m *MessageEvent) Reset()                    { *m = MessageEvent{} }
func (m *MessageEvent) String() string            { return proto.CompactTextString(m) }
func (*MessageEvent) ProtoMessage()               {}
func (*MessageEvent) Descriptor() ([]byte, []int) { return fileDescriptorAccessors, []int{0} }

func (m *MessageEvent) GetSender() *MessageEvent_Sender {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *MessageEvent) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *MessageEvent) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

// Sender is who sent the message.
type MessageEvent_Sender struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MessageEvent_Sender) Reset()                    { *m = MessageEvent_Sender{} }
func (m *MessageEvent_Sender) String() string            { return proto.CompactTextString(m) }
func (*MessageEvent_Sender) ProtoMessage()               {}
func (*MessageEvent_Sender) Descriptor() ([]byte, []int) { return fileDescriptorAccessors, []int{0, 0} }

func (m *MessageEvent_Sender) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MessageEvent_Sender) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*MessageEvent)(nil), "accessors.MessageEvent")
	proto.RegisterType((*MessageEvent_Sender)(nil), "accessors.MessageEvent.Sender")
}

func init() { proto.RegisterFile("accessors.proto", fileDescriptorAccessors) }

var fileDescriptorAccessors = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x4c, 0x4e, 0x4e,
	0x2d, 0x2e, 0xce, 0x2f, 0x2a, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0x2d, 0x60, 0xe4, 0xe2, 0xf1, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x75, 0x2d, 0x4b, 0xcd, 0x2b,
	0x11, 0x32, 0xe3, 0x62, 0x2b, 0x4e, 0xcd, 0x4b, 0x49, 0x2d, 0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x36, 0x92, 0xd3, 0x43, 0xe8, 0x46, 0x56, 0xa8, 0x17, 0x0c, 0x56, 0x15, 0x04, 0x55, 0x2d, 0x24,
	0xc6, 0xc5, 0x96, 0x5f, 0x94, 0x99, 0x9e, 0x99, 0x27, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04,
	0xe5, 0x09, 0x09, 0x71, 0xb1, 0x24, 0xe5, 0xa7, 0x54, 0x4a, 0x30, 0x83, 0x45, 0xc1, 0x6c, 0x29,
	0x1d, 0x2e, 0x36, 0x88, 0x6e, 0x90, 0x6c, 0x5e, 0x62, 0x6e, 0x2a, 0xd8, 0x2e, 0xce, 0x20, 0x30,
	0x5b, 0x88, 0x8f, 0x8b, 0x29, 0x33, 0x05, 0x6a, 0x0a, 0x53, 0x66, 0x8a, 0x13, 0x77, 0x14, 0xc2,
	0xbd, 0x49, 0x6c, 0x60, 0x1f, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x3c, 0x9b, 0x99,
	0xd4, 0x00, 0x00, 0x00,
}
