// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user.proto

package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// BaseUser is an abstract representation of a user, both for network and database purposes.
type BaseUser struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Permissions          []string `protobuf:"bytes,10,rep,name=permissions" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseUser) Reset()         { *m = BaseUser{} }
func (m *BaseUser) String() string { return proto.CompactTextString(m) }
func (*BaseUser) ProtoMessage()    {}
func (*BaseUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_24d869ed827e2142, []int{0}
}
func (m *BaseUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseUser.Unmarshal(m, b)
}
func (m *BaseUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseUser.Marshal(b, m, deterministic)
}
func (dst *BaseUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseUser.Merge(dst, src)
}
func (m *BaseUser) XXX_Size() int {
	return xxx_messageInfo_BaseUser.Size(m)
}
func (m *BaseUser) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseUser.DiscardUnknown(m)
}

var xxx_messageInfo_BaseUser proto.InternalMessageInfo

func (m *BaseUser) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *BaseUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BaseUser) GetPermissions() []string {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func init() {
	proto.RegisterType((*BaseUser)(nil), "justanotherbotkit_proto.BaseUser")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_user_24d869ed827e2142) }

var fileDescriptor_user_24d869ed827e2142 = []byte{
	// 135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xcf, 0x2a, 0x2d, 0x2e, 0x49, 0xcc, 0xcb, 0x2f,
	0xc9, 0x48, 0x2d, 0x4a, 0xca, 0x2f, 0xc9, 0xce, 0x2c, 0x89, 0x07, 0x4b, 0x28, 0x05, 0x70, 0x71,
	0x38, 0x25, 0x16, 0xa7, 0x86, 0x16, 0xa7, 0x16, 0x09, 0xf1, 0x71, 0x31, 0x79, 0xba, 0x48, 0x30,
	0x2a, 0x30, 0x6a, 0x70, 0x06, 0x31, 0x79, 0xba, 0x08, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6,
	0x4a, 0x30, 0x81, 0x45, 0xc0, 0x6c, 0x21, 0x05, 0x2e, 0xee, 0x82, 0xd4, 0xa2, 0xdc, 0xcc, 0xe2,
	0xe2, 0xcc, 0xfc, 0xbc, 0x62, 0x09, 0x2e, 0x05, 0x66, 0x0d, 0xce, 0x20, 0x64, 0x21, 0x27, 0x96,
	0x28, 0xa6, 0x82, 0xa4, 0x24, 0x36, 0xb0, 0xf1, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd3,
	0x31, 0x54, 0x52, 0x85, 0x00, 0x00, 0x00,
}
